<?xml version="1.0"?>
<robot name="holonomicdrive" xmlns:xacro="http://ros.org/wiki/xacro">
  
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>

  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
    </inertial>
  </xacro:macro>
  
<!-- x axis red, y axis green -->
  <!-- <xacro:property name="pi" value="3.1415926" /> -->
  <xacro:property name="base_side_length" value="1" />
  <xacro:property name="wheel_offset" value="${ (((base_side_length * base_side_length)/2) ** 0.5)/2}" />

  <xacro:property name="wheel_width" value = "${0.05}"/>
  <xacro:property name="wheel_width_offset" value = "${ (((wheel_width/2) * (wheel_width/2))/2) ** 0.5}"/>

  <link name="base_link">
    <visual>
      <geometry>
        <box size = "${base_side_length} ${base_side_length} 0.2"/>
      </geometry>
      <material name = "white"/>
      <origin xyz = "0 0 0" rpy = "0 0 ${pi/4}"/>
    </visual> 
    <collision>
      <geometry>
        <box size = "${base_side_length} ${base_side_length} 0.2"/>
      </geometry>
      <origin xyz = "0 0 0" rpy = "0 0 ${pi/4}"/>
    </collision>
    <xacro:default_inertial mass="8"/>
  </link>

  <link name="turret">
    <visual>
      <geometry>
        <cylinder radius="0.25" length="0.1"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.25" length="0.1"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="1"/>
  </link>

  <joint name="turret_joint" type="continuous">
    <parent link="base_link"/>
    <child link="turret"/>
    <origin xyz="0.0 0.0 0.15"/>
    <axis xyz="0.0 0.0 1"/>
    <limit effort="30" velocity="1.0"/>
    <dynamics damping="0.0" friction="0.1"/>
    <!-- <kp value = '1'/> -->
  </joint>

  <transmission name="turret_swivel_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <actuator name="$turret_swivel_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    <joint name="turret_joint">
      <hardwareInterface>VelocityJointInterface</hardwareInterface>
    </joint>
  </transmission>

  <link name="turret_bar">
    <visual>
      <geometry>
        <box size="0.7 0.1 0.1"/>
      </geometry> 
      <material name="white"/>
      <origin rpy="0.0 0.0 ${pi/2}"/>
    </visual> 
      <collision>
        <geometry>
        <box size="0.7 0.1 0.1"/>
      </geometry>  
      <origin rpy="0.0 0.0 ${pi/2}"/>
    </collision>
  </link>

  <joint name="turret_to_bar_link" type="fixed">
    <parent link="turret"/>
    <child link="turret_bar"/>
    <origin xyz="0 0.25 0.1"/>
  </joint>


  <link name="right_front_wheel">
    <visual>
      <geometry>
        <cylinder radius = "0.075" length = "0.05"/>
      </geometry>
      <material name = "black"/>
      <origin rpy="0 ${pi/2} ${(pi/4) + pi}"/>
    </visual> 
    <collision>
     <geometry>
        <cylinder radius = "0.075" length = "0.05"/>
      </geometry>
      <origin rpy="0 ${pi/2} ${(pi/4) + pi}"/>
    </collision>
    <xacro:default_inertial mass="1"/>
  </link>

  <joint name="right_front_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_front_wheel"/>   
    <origin xyz = "${wheel_offset + wheel_width_offset} ${wheel_offset + wheel_width_offset} -0.075"/>
    <axis xyz ="1 1 0"/>
    <limit effort="30" velocity="100"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <transmission name="right_front_wheel_trans">
    <type>SimpleTransmission</type>
    <actuator name="right_front_wheel_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    <joint name="right_front_wheel_joint">
      <hardwareInterface>VelocityJointInterface</hardwareInterface>
    </joint>
  </transmission>


  <link name="left_front_wheel">
    <visual>
      <geometry>
        <cylinder radius = "0.075" length = "0.05"/>
      </geometry>
      <material name = "black"/>
      <origin rpy="0 ${pi/2} ${-pi/4}"/>
    </visual> 
    <collision>
     <geometry>
        <cylinder radius = "0.075" length = "0.05"/>
      </geometry>
      <origin rpy="0 ${pi/2} ${-pi/4}"/>
    </collision>
    <xacro:default_inertial mass="1"/>
  </link>

  <joint name="left_front_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_front_wheel"/>   
    <origin xyz = "${- wheel_offset - wheel_width_offset} ${wheel_offset + wheel_width_offset} -0.075"/>
    <axis xyz ="-1 1 0"/>
    <limit effort="30" velocity="100"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <transmission name="left_front_wheel_trans">
    <type>SimpleTransmission</type>
    <actuator name="left_front_wheel_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    <joint name="left_front_wheel_joint">
      <hardwareInterface>VelocityJointInterface</hardwareInterface>
    </joint>
  </transmission>


  <link name="left_back_wheel">
    <visual>
      <geometry>
        <cylinder radius = "0.075" length = "0.05"/>
      </geometry>
      <material name = "black"/>
      <origin rpy="0 ${pi/2} ${pi/4}"/>
    </visual> 
    <collision>
     <geometry>
        <cylinder radius = "0.075" length = "0.05"/>
      </geometry>
      <origin rpy="0 ${pi/2} ${pi/4}"/>
    </collision>
    <xacro:default_inertial mass="1"/>
  </link>

  <joint name="left_back_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_back_wheel"/>   
    <origin xyz = "${- wheel_offset - wheel_width_offset} ${-wheel_offset - wheel_width_offset} -0.075"/>
    <axis xyz ="-1 -1 0"/>
    <limit effort="30" velocity="100"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <transmission name="left_back_wheel_trans">
    <type>SimpleTransmission</type>
    <actuator name="left_back_wheel_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    <joint name="left_back_wheel_joint">
      <hardwareInterface>VelocityJointInterface</hardwareInterface>
    </joint>
  </transmission>


  <link name="right_back_wheel">
    <visual>
      <geometry>
        <cylinder radius = "0.075" length = "0.05"/>
      </geometry>
      <material name = "black"/>
      <origin rpy="0 ${pi/2} ${(-pi/4) + (pi)}"/>
    </visual> 
    <collision>
     <geometry>
        <cylinder radius = "0.075" length = "0.05"/>
      </geometry>
      <origin rpy="0 ${pi/2} ${(-pi/4) + pi}"/>
    </collision>
    <xacro:default_inertial mass="1"/>
  </link>

  <joint name="right_back_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_back_wheel"/>   
    <origin xyz = "${wheel_offset + wheel_width_offset} ${-wheel_offset - wheel_width_offset} -0.075"/>
    <axis xyz ="1 -1 0"/>
    <limit effort="30" velocity="100"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <transmission name="right_back_wheel_trans">
    <type>SimpleTransmission</type>
    <actuator name="right_back_wheel_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    <joint name="right_back_wheel_joint">
      <hardwareInterface>VelocityJointInterface</hardwareInterface>
    </joint>
  </transmission>


  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/</robotNamespace>
    </plugin>
  </gazebo>

</robot>
